import type { Metadata } from 'next';
import { Josefin_Sans, Miniver } from 'next/font/google';
import './globals.css';

const josefinSans = Josefin_Sans({
  variable: '--font-primary',
  subsets: ['latin'],
  display: 'swap',
});

const miniver = Miniver({
  variable: '--font-secondary',
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${josefinSans.variable} ${miniver.variable} antialiased`}>{children}</body>
    </html>
  );
}
